version: '2'

volumes:
  orderer2.mynetwork.com:
  peer1.org1.mynetwork.com:

networks:
  mynetwork:

services:
  orderer2.mynetwork.com:
    container_name: orderer2.mynetwork.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=10020
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - /root/git/src/mynetwork/instance1/data/channel-artifacts/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /root/git/src/mynetwork/instance1/data/cryptofile/ordererOrganizations/mynetwork.com/orderers/orderer2.mynetwork.com/msp:/var/hyperledger/orderer/msp
        - /root/git/src/mynetwork/instance1/data/cryptofile/ordererOrganizations/mynetwork.com/orderers/orderer2.mynetwork.com/tls/:/var/hyperledger/orderer/tls
        #- orderer2.mynetwork.com:/var/hyperledger/production/orderer
        #- /root/git/src/mynetwork/instance1/volume/orderer2.mynetwork.com:/var/hyperledger/production/orderer
    ports:
      - 10020:10020
    networks:
      - mynetwork
    extra_hosts:
      - orderer1.mynetwork.com:10.140.0.11
      - orderer2.mynetwork.com:10.140.0.12
      - orderer3.mynetwork.com:10.128.0.3
      - peer1.org1.mynetwork.com:10.140.0.12
      - peer1.org2.mynetwork.com:10.128.0.3
      - peer2.org2.mynetwork.com:10.128.0.3
      
  peer1.org1.mynetwork.com:
    container_name: peer1.org1.mynetwork.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mynetwork
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.org1.mynetwork.com
      - CORE_PEER_ADDRESS=peer1.org1.mynetwork.com:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.mynetwork.com:17052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:17052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.mynetwork.com:17051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.mynetwork.com:17051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - /root/git/src/mynetwork/instance1/data/cryptofile/peerOrganizations/org1.mynetwork.com/peers/peer1.org1.mynetwork.com/msp:/etc/hyperledger/fabric/msp
        - /root/git/src/mynetwork/instance1/data/cryptofile/peerOrganizations/org1.mynetwork.com/peers/peer1.org1.mynetwork.com/tls:/etc/hyperledger/fabric/tls
        #- /root/git/src/mynetwork/instance1/volume/peer1.org1.mynetwork.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 17051:17051
      - 17052:17052
    networks:
      - mynetwork
    extra_hosts:
      - orderer1.mynetwork.com:10.140.0.11
      - orderer2.mynetwork.com:10.140.0.12
      - orderer3.mynetwork.com:10.128.0.3
      - peer1.org1.mynetwork.com:10.140.0.12
      - peer1.org2.mynetwork.com:10.128.0.3
      - peer2.org2.mynetwork.com:10.128.0.3